### ISSUE TITLE
DevTools Helper Issue and remote access to mobile browser

### ISSUE THREAD

**Issue by musabu** [glennschler/remote-devtools-har#5]
I have been trying to run remote-devtools-har on my Ubuntu box using the example provided on the npm website, https://www.npmjs.com/package/remote-devtools-har, but I keep getting the error "Cannot find module './DevToolsHelper'" (see attached). There don't seem to be any package with that name available online for me to install.

My main target is to eventually use your tool to collect HAR logs from a mobile chrome browser of an android phone in an automatic manner. What I mean is the remote object to be accessed here should be the Chrome browser running on an android, which is directly connected to the Ubuntu Desktop I am using.

Do you think your tool can enable that? Or if you can point me to any tool that can help? Or ideas on how to go about collecting the logs a number of times to use in some evaluation.

Many thanks.

**Comment by glennschler** [comment]
Resolved primary issue by using the case-sensitive `devToolsHelper` module name

Yes, this should be able to collect from a remote chrome running on Android. If you start that Chrome with the correct arguments. Though that use case has not been tested. Please create a new issue if it does not work.
